version: '3.9'
services:

  frontend:
    image: puzynjailya/todolist_front
    restart: always
    depends_on:
      api:
        condition: service_healthy
    ports:
      - 80:80
    volumes:
      - /todo-list-frontend/docker/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - frontend_net

  api:
    image: puzynjailya/todolist:$GITHUB_RUN_ID
    restart: always
    env_file:
      - .env
    depends_on:
      pg:
        condition: service_healthy
    command: python manage.py runserver 0.0.0.0:8000
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
    networks:
      - backend_net
      - frontend_net

  migrations:
    image: puzynjailya/todolist:$GITHUB_RUN_ID
    env_file:
      - .env
    depends_on:
      pg:
        condition: service_healthy
    command: bash -c "
             python manage.py makemigrations &&  
             python manage.py migrate"
    networks:
      - backend_net

  pg:
    image: postgres:14.5-alpine
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_DB: $DB_NAME
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
    volumes:
      - /postgres_data/:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U $DB_USER -d $DB_NAME
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - backend_net

volumes:
  postgres_data:

networks:
  backend_net:
    driver: bridge
  frontend_net:
    driver: bridge

