# Generated by Django 4.1 on 2022-10-14 20:50

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("goals", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Board",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(verbose_name="Дата создания")),
                (
                    "updated",
                    models.DateTimeField(verbose_name="Дата последнего обновления"),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=255,
                        validators=[django.core.validators.MinLengthValidator(1)],
                        verbose_name="Название",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Удалена"),
                ),
            ],
            options={
                "verbose_name": "Доска",
                "verbose_name_plural": "Доски",
            },
        ),
        migrations.CreateModel(
            name="Goal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(verbose_name="Дата создания")),
                (
                    "updated",
                    models.DateTimeField(verbose_name="Дата последнего обновления"),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Название")),
                (
                    "description",
                    models.TextField(
                        blank=True, max_length=2000, null=True, verbose_name="Описание"
                    ),
                ),
                (
                    "status",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "К выполнению"),
                            (2, "В процессе"),
                            (3, "Выполнено"),
                            (4, "Архив"),
                        ],
                        default=1,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "priority",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Низкий"),
                            (2, "Средний"),
                            (3, "Высокий"),
                            (4, "Критический"),
                        ],
                        default=2,
                        verbose_name="Приоритет",
                    ),
                ),
                ("due_date", models.DateTimeField(verbose_name="Дата дедлайна")),
            ],
            options={
                "verbose_name": "Цель",
                "verbose_name_plural": "Цели",
            },
        ),
        migrations.RenameField(
            model_name="goalcategory",
            old_name="created_date",
            new_name="created",
        ),
        migrations.RenameField(
            model_name="goalcategory",
            old_name="last_update_date",
            new_name="updated",
        ),
        migrations.AlterField(
            model_name="goalcategory",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Автор",
            ),
        ),
        migrations.CreateModel(
            name="GoalComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(verbose_name="Дата создания")),
                (
                    "updated",
                    models.DateTimeField(verbose_name="Дата последнего обновления"),
                ),
                ("text", models.TextField(max_length=255, verbose_name="Текст")),
                (
                    "goal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="goals.goal",
                        verbose_name="цель",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Автор",
                    ),
                ),
            ],
            options={
                "verbose_name": "Комментарий",
                "verbose_name_plural": "Комментарии",
            },
        ),
        migrations.AddField(
            model_name="goal",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="goals",
                to="goals.goalcategory",
                verbose_name="Категория",
            ),
        ),
        migrations.AddField(
            model_name="goal",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Автор",
            ),
        ),
        migrations.AddField(
            model_name="goalcategory",
            name="board",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="categories",
                to="goals.board",
                verbose_name="Доска",
            ),
        ),
        migrations.CreateModel(
            name="BoardParticipant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(verbose_name="Дата создания")),
                (
                    "updated",
                    models.DateTimeField(verbose_name="Дата последнего обновления"),
                ),
                (
                    "role",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "Владелец"), (2, "Редактор"), (3, "Читатель")],
                        default=3,
                        verbose_name="Role",
                    ),
                ),
                (
                    "board",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="participants",
                        to="goals.board",
                        verbose_name="Доска",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="participants",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Участник",
                "verbose_name_plural": "Участники",
                "unique_together": {("user", "board")},
            },
        ),
    ]
