# Generated by Django 4.1 on 2022-10-02 21:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("goals", "0002_alter_goalcategory_user_goal"),
    ]

    operations = [
        migrations.AddField(
            model_name="goal",
            name="user",
            field=models.ForeignKey(
                default=3,
                on_delete=django.db.models.deletion.RESTRICT,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Автор",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="goal",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="goals.goalcategory",
                verbose_name="Категория",
            ),
        ),
        migrations.AlterField(
            model_name="goal",
            name="description",
            field=models.TextField(
                blank=True, max_length=2000, null=True, verbose_name="Описание"
            ),
        ),
    ]
