# Generated by Django 4.1 on 2022-10-14 20:50

from django.db import migrations, transaction
from django.utils import timezone


def create_objects(apps, schema_editor):
    """
    Для загрузки кода моделей используется специальный метод apps.get_model
    Он позволяет загрузить ровно то состояние модели, которое было на момент применения этой миграции
    Импортировать настоящие классы – плохая практика
    так как в будущем вы можете удалить/переименовать эти модели, и тогда у вас будут ошибки импорта
    """

    User = apps.get_model('core', 'User')
    Board = apps.get_model('goals', 'Board')
    BoardParticipant = apps.get_model('goals', 'BoardParticipant')
    GoalCategory = apps.get_model('goals', 'GoalCategory')

    # Применяем все изменения одной транзакцией
    with transaction.atomic():
        for user in User.objects.all():
            new_board = Board.objects.create(
                title="Мои цели",
                created=timezone.now(),
                update=timezone.now()
            )
            BoardParticipant.objects.create(
                user=user,
                board=new_board,
                role=1,
                created=timezone.now(),
                update=timezone.now()
            )
            GoalCategory.object.filter(user=user).update(board=new_board)


class Migration(migrations.Migration):

    dependencies = [
        ("goals", "0002_board_goal_rename_created_date_goalcategory_created_and_more"),
    ]

    operations = [migrations.RunPython(create_objects)]
