# Generated by Django 4.1 on 2022-10-04 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("goals", "0003_goal_user_alter_goal_category_alter_goal_description"),
    ]

    operations = [
        migrations.RenameField(
            model_name="goal",
            old_name="dead_line_date",
            new_name="due_date",
        ),
    ]
