# Generated by Django 4.1 on 2022-10-05 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("goals", "0004_rename_dead_line_date_goal_due_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="goal",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="goals",
                to="goals.goalcategory",
                verbose_name="Категория",
            ),
        ),
    ]
