# Generated by Django 4.1 on 2022-10-06 21:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("goals", "0005_alter_goal_category"),
    ]

    operations = [
        migrations.RenameField(
            model_name="goal",
            old_name="created_date",
            new_name="created",
        ),
        migrations.RenameField(
            model_name="goal",
            old_name="last_update_date",
            new_name="updated",
        ),
        migrations.RenameField(
            model_name="goalcategory",
            old_name="created_date",
            new_name="created",
        ),
        migrations.RenameField(
            model_name="goalcategory",
            old_name="last_update_date",
            new_name="updated",
        ),
        migrations.CreateModel(
            name="GoalComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(verbose_name="Дата создания")),
                (
                    "updated",
                    models.DateTimeField(verbose_name="Дата последнего обновления"),
                ),
                ("text", models.TextField(max_length=255, verbose_name="Текст")),
                (
                    "goal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="goals.goal",
                        verbose_name="цель",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Автор",
                    ),
                ),
            ],
            options={
                "verbose_name": "Комментарий",
                "verbose_name_plural": "Комментарии",
            },
        ),
    ]
